"""empty message

Revision ID: 82bc6d39fef5
Revises: 9269c11019f9
Create Date: 2021-09-14 15:42:56.182040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bc6d39fef5'
down_revision = '9269c11019f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_following', sa.Column('createdAt', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_following', 'createdAt')
    # ### end Alembic commands ###
