"""empty message

Revision ID: 3e7d772f9d50
Revises: 82bc6d39fef5
Create Date: 2021-09-14 15:44:21.607709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7d772f9d50'
down_revision = '82bc6d39fef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('createdAt', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'createdAt')
    # ### end Alembic commands ###
