"""empty message

Revision ID: eedd295a5a3a
Revises: ffdc0a98111c
Create Date: 2021-09-12 14:59:47.866788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedd295a5a3a'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followingUserId', sa.Integer(), nullable=True),
    sa.Column('followerUserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followerUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['followingUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('profileImgUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImgUrl')
    op.drop_table('follows')
    # ### end Alembic commands ###
