"""empty message

Revision ID: 63d400c5b668
Revises: 5661a79eb852
Create Date: 2021-09-12 15:46:21.667035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d400c5b668'
down_revision = '5661a79eb852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imageTags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgId', sa.Integer(), nullable=True),
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imgId'], ['images.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('imgId', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('content', sa.String(length=255), nullable=False))
    op.add_column('comments', sa.Column('edited', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('createdAt', sa.Time(), nullable=True))
    op.create_foreign_key(None, 'comments', 'images', ['imgId'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'createdAt')
    op.drop_column('comments', 'edited')
    op.drop_column('comments', 'content')
    op.drop_column('comments', 'imgId')
    op.drop_column('comments', 'userId')
    op.drop_table('imageTags')
    op.drop_table('tags')
    # ### end Alembic commands ###
